-- =====================================================================
-- Cuidar+ / IntegraTEA · Migração 003 · 17/09/2026
-- Rodar depois da 001 e da 002. Idempotente.
--
-- 1. Campos das fichas do NASF e do NAPE exigidos no edital (Anexo A.1 a A.5)
-- 2. Informação clínica do paciente em tabela separada (só equipe clínica)
-- 3. Cadastro (create_patient) com os novos campos
-- 4. Base pública do assistente de WhatsApp (agent_knowledge)
-- 5. Visão pública e agregada da rede para a API /api/v1/publico (sem dado pessoal)
-- =====================================================================

set search_path = public, extensions;

-- ---------------------------------------------------------------------
-- 1. Ficha NASF (prontuário) e NAPE (identificação escolar)
-- ---------------------------------------------------------------------
alter table public.patients
  add column if not exists record_number bigint generated by default as identity,
  add column if not exists phone text,
  add column if not exists race_color text check (race_color in ('branca','preta','parda','amarela','indigena','nao_informado')),
  add column if not exists municipality text not null default 'Crateús',
  add column if not exists state char(2) not null default 'CE',
  add column if not exists guardian_cns text,
  add column if not exists guardian_birth_date date,
  add column if not exists school_grade text,
  add column if not exists school_shift text check (school_shift in ('manha','tarde','noite','integral')),
  add column if not exists zone text check (zone in ('urbana','rural')),
  add column if not exists record_opened_at date not null default current_date;

create unique index if not exists patients_record_number_key on public.patients (record_number);
update public.patients set record_opened_at = created_at::date where record_opened_at = current_date and created_at::date <> current_date;

-- ---------------------------------------------------------------------
-- 2. Informação clínica (H.D., medicação em uso) separada da identificação
-- ---------------------------------------------------------------------
create table if not exists public.patient_clinical_info (
  patient_id uuid primary key references public.patients(id),
  diagnostic_hypothesis text,
  medications text,
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);
alter table public.patient_clinical_info enable row level security;
drop policy if exists clinical_info_select on public.patient_clinical_info;
create policy clinical_info_select on public.patient_clinical_info for select to authenticated
  using ((select public.is_clinical()));
grant select on public.patient_clinical_info to authenticated;

drop trigger if exists trg_block_delete on public.patient_clinical_info;
create trigger trg_block_delete before delete on public.patient_clinical_info
  for each row execute function cuidar_private.tg_block_delete();
drop trigger if exists trg_audit on public.patient_clinical_info;
create trigger trg_audit after insert or update on public.patient_clinical_info
  for each row execute function cuidar_private.tg_audit();

create or replace function cuidar_private.tg_clinical_revision() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_version int;
begin
  if to_jsonb(old) - 'updated_at' = to_jsonb(new) - 'updated_at' then return null; end if;
  select coalesce(max(version), 0) + 1 into v_version
  from public.record_revisions where table_name = 'patient_clinical_info' and record_id = old.patient_id;
  insert into public.record_revisions (table_name, record_id, version, changed_fields, old_data, new_data, changed_by)
  values ('patient_clinical_info', old.patient_id, v_version, array['diagnostic_hypothesis', 'medications'], to_jsonb(old), to_jsonb(new), auth.uid());
  return null;
end $$;
drop trigger if exists trg_revision on public.patient_clinical_info;
create trigger trg_revision after update on public.patient_clinical_info
  for each row execute function cuidar_private.tg_clinical_revision();

create or replace function public.save_clinical_info(p_patient uuid, p_hypothesis text, p_medications text)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public.assert_role('profissional','coordenacao','admin');
  insert into public.patient_clinical_info (patient_id, diagnostic_hypothesis, medications, updated_by, updated_at)
  values (p_patient, nullif(btrim(p_hypothesis), ''), nullif(btrim(p_medications), ''), auth.uid(), now())
  on conflict (patient_id) do update
    set diagnostic_hypothesis = excluded.diagnostic_hypothesis, medications = excluded.medications,
        updated_by = excluded.updated_by, updated_at = now();
end $$;
revoke all on function public.save_clinical_info(uuid, text, text) from public, anon;
grant execute on function public.save_clinical_info(uuid, text, text) to authenticated;

-- ---------------------------------------------------------------------
-- 3. Cadastro com os campos das fichas
-- ---------------------------------------------------------------------
create or replace function public.create_patient(p_data jsonb) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
  v_cns text := nullif(regexp_replace(coalesce(p_data ->> 'cns', ''), '\D', '', 'g'), '');
  v_cpf text := nullif(regexp_replace(coalesce(p_data ->> 'cpf', ''), '\D', '', 'g'), '');
  v_gcns text := nullif(regexp_replace(coalesce(p_data ->> 'guardian_cns', ''), '\D', '', 'g'), '');
begin
  perform public.assert_role('recepcao','profissional','coordenacao','admin');

  if not exists (select 1 from public.audit_logs
                 where user_id = auth.uid() and action = 'patient.search' and created_at > now() - interval '30 minutes') then
    raise exception 'Antes de cadastrar, faça uma busca para confirmar que a pessoa ainda não está no sistema.' using errcode = 'P0001';
  end if;
  if v_cns is not null and exists (select 1 from public.patients where cns = v_cns) then
    raise exception 'Já existe um paciente com este CNS. Abra o cadastro existente.' using errcode = '23505';
  end if;
  if v_cpf is not null and exists (select 1 from public.patients where cpf = v_cpf) then
    raise exception 'Já existe um paciente com este CPF. Abra o cadastro existente.' using errcode = '23505';
  end if;
  if coalesce(btrim(p_data ->> 'full_name'), '') = '' or coalesce(btrim(p_data ->> 'mother_name'), '') = ''
     or (p_data ->> 'birth_date') is null then
    raise exception 'Nome, data de nascimento e nome da mãe são obrigatórios.' using errcode = '22023';
  end if;

  insert into public.patients (full_name, social_name, birth_date, mother_name, cns, cpf, sex, race_color, phone,
    guardian_name, guardian_phone, guardian_relationship, guardian_cns, guardian_birth_date,
    aps_reference, address, neighborhood, municipality, state, zone, school_name, school_grade, school_shift, created_by)
  values (p_data ->> 'full_name', nullif(btrim(p_data ->> 'social_name'), ''), (p_data ->> 'birth_date')::date,
    p_data ->> 'mother_name', v_cns, v_cpf, nullif(p_data ->> 'sex', ''), nullif(p_data ->> 'race_color', ''),
    nullif(btrim(p_data ->> 'phone'), ''),
    nullif(btrim(p_data ->> 'guardian_name'), ''), nullif(btrim(p_data ->> 'guardian_phone'), ''),
    nullif(btrim(p_data ->> 'guardian_relationship'), ''), v_gcns, nullif(p_data ->> 'guardian_birth_date', '')::date,
    nullif(btrim(p_data ->> 'aps_reference'), ''), nullif(btrim(p_data ->> 'address'), ''), nullif(btrim(p_data ->> 'neighborhood'), ''),
    coalesce(nullif(btrim(p_data ->> 'municipality'), ''), 'Crateús'), coalesce(nullif(btrim(p_data ->> 'state'), ''), 'CE'),
    nullif(p_data ->> 'zone', ''), nullif(btrim(p_data ->> 'school_name'), ''), nullif(btrim(p_data ->> 'school_grade'), ''),
    nullif(p_data ->> 'school_shift', ''), auth.uid())
  returning id into v_id;

  if coalesce(btrim(p_data ->> 'diagnostic_hypothesis'), '') <> '' and public.is_clinical() then
    insert into public.patient_clinical_info (patient_id, diagnostic_hypothesis, updated_by)
    values (v_id, btrim(p_data ->> 'diagnostic_hypothesis'), auth.uid());
  end if;
  return v_id;
end $$;

-- ---------------------------------------------------------------------
-- 4. Base pública do assistente de WhatsApp (mesma estrutura do bot)
-- ---------------------------------------------------------------------
create table if not exists public.agent_knowledge (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  service text,
  audience text not null default 'publico',
  published boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.agent_knowledge enable row level security;
drop policy if exists agent_knowledge_admin on public.agent_knowledge;
create policy agent_knowledge_admin on public.agent_knowledge for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists agent_knowledge_read on public.agent_knowledge;
create policy agent_knowledge_read on public.agent_knowledge for select to authenticated using (published or (select public.is_admin()));
grant select, insert, update on public.agent_knowledge to authenticated;

create index if not exists agent_knowledge_search_idx
  on public.agent_knowledge using gin (
    to_tsvector('portuguese', coalesce(title, '') || ' ' || coalesce(content, '') || ' ' || coalesce(service, ''))
  );

create or replace function public.search_agent_knowledge(search_query text, result_limit integer default 5)
returns table (title text, content text, service text, audience text, updated_at timestamptz)
language sql stable set search_path = public, extensions
as $$
  with q as (select websearch_to_tsquery('portuguese', left(coalesce(search_query, ''), 500)) as tsq,
                    public.f_norm(search_query) as norm)
  select k.title, k.content, k.service, k.audience, k.updated_at
  from public.agent_knowledge k, q
  where k.published = true
    and (to_tsvector('portuguese', coalesce(k.title, '') || ' ' || coalesce(k.content, '') || ' ' || coalesce(k.service, '')) @@ q.tsq
         or public.f_norm(k.title || ' ' || coalesce(k.service, '')) % q.norm)
  order by ts_rank(to_tsvector('portuguese', coalesce(k.title, '') || ' ' || coalesce(k.content, '') || ' ' || coalesce(k.service, '')), q.tsq) desc,
           k.updated_at desc
  limit least(greatest(result_limit, 1), 8);
$$;
revoke all on function public.search_agent_knowledge(text, integer) from public, anon, authenticated;
grant execute on function public.search_agent_knowledge(text, integer) to service_role;

insert into public.agent_knowledge (title, content, service, audience, published)
select * from (values
  ('O que é o IntegraTEA', 'O IntegraTEA coordena a jornada de cuidado de pessoas com TEA na rede municipal de Crateús, integrando NASF, NAPE, CREAES, Casa Mais Azul e CRASF em um cadastro único, com filas, agenda, encaminhamentos e acompanhamento.', 'Rede IntegraTEA', 'publico', true),
  ('Limites do atendimento pelo WhatsApp', 'O canal fornece orientações gerais. Ele não realiza diagnóstico, prescrição, decisão clínica nem consulta prontuário, posição individual em fila ou agenda pessoal.', 'Rede IntegraTEA', 'publico', true),
  ('Urgência médica', 'Em situação de urgência ou risco imediato, ligue gratuitamente para o SAMU 192 ou procure o serviço de urgência mais próximo.', 'SAMU', 'publico', true),
  ('Como entrar na rede de cuidado', 'O primeiro passo é procurar a Unidade Básica de Saúde (UBS) do seu bairro ou a escola, que podem encaminhar para a rede. Leve documento com foto, Cartão SUS (CNS) e, se tiver, relatórios anteriores. A equipe faz a triagem e informa o próximo passo. [Conteúdo de demonstração: validar com a Secretaria de Saúde.]', 'Rede IntegraTEA', 'publico', true),
  ('NASF', 'O NASF (Núcleo Ampliado de Saúde da Família) apoia as equipes de saúde da família com atendimento multiprofissional, como fonoaudiologia, psicologia, fisioterapia, nutrição e serviço social. O acesso é pela UBS de referência. [Demonstração: validar endereço e horário.]', 'NASF', 'publico', true),
  ('NAPE', 'O NAPE (Núcleo de Atendimento Pedagógico Especializado), da Secretaria de Educação, atende estudantes com TEA e outras necessidades educacionais, com psicopedagogia, psicologia, AEE, fonoaudiologia e educação física adaptada. O encaminhamento costuma ser feito pela escola. [Demonstração: validar contatos.]', 'NAPE', 'publico', true),
  ('CREAES', 'O CREAES é o centro de referência especializado da rede, com neuropediatria, psiquiatria infantojuvenil, terapia ocupacional, fonoaudiologia e psicologia. O acesso é por encaminhamento de outro serviço da rede. [Demonstração: validar nome oficial e contatos.]', 'CREAES', 'publico', true),
  ('Casa Mais Azul', 'A Casa Mais Azul é um espaço de acolhimento e convivência, com atividades como musicoterapia, educação física adaptada e terapia ocupacional em grupo. [Demonstração: validar horários e forma de acesso.]', 'Casa Mais Azul', 'publico', true),
  ('CRASF', 'O CRASF apoia as famílias com serviço social e psicologia, incluindo orientação sobre benefícios e direitos. [Demonstração: validar nome oficial e contatos.]', 'CRASF', 'publico', true),
  ('Documentos para o atendimento', 'Leve documento com foto da pessoa atendida e do responsável, Cartão SUS (CNS), comprovante de endereço e relatórios ou exames que já tiver. [Demonstração: validar a lista oficial.]', 'Rede IntegraTEA', 'publico', true),
  ('Faltas e remarcação', 'Se não puder comparecer, avise o serviço com antecedência para remarcar. Faltas seguidas sem aviso fazem a equipe entrar em contato para entender se há alguma dificuldade de acesso, como transporte.', 'Rede IntegraTEA', 'publico', true),
  ('Tempo de espera', 'A fila de cada serviço é organizada por prioridade definida por profissional e pelo tempo de espera. O WhatsApp informa apenas a média geral de espera por serviço; a situação individual deve ser consultada presencialmente.', 'Rede IntegraTEA', 'publico', true)
) as seed(title, content, service, audience, published)
where not exists (select 1 from public.agent_knowledge where title = seed.title);

-- ---------------------------------------------------------------------
-- 5. Visão pública da rede (somente agregados, sem dado pessoal)
-- ---------------------------------------------------------------------
create or replace function public.public_network_overview()
returns jsonb
language sql stable security definer set search_path = public
as $$
  select jsonb_build_object(
    'atualizado_em', now(),
    'aviso', 'Dados agregados e fictícios para demonstração. Não contém informação individual.',
    'servicos', coalesce((
      select jsonb_agg(jsonb_build_object(
        'codigo', s.code, 'nome', s.name, 'descricao', s.description, 'secretaria', s.secretaria,
        'endereco', s.address, 'telefone', s.phone,
        'especialidades', coalesce((
          select jsonb_agg(jsonb_build_object(
            'nome', sp.name,
            'vagas_mes', ss.monthly_capacity,
            -- faixas em vez de números exatos quando a fila é pequena (evita reidentificação)
            'pessoas_aguardando', case when w.waiting < 5 then 'menos de 5' else w.waiting::text end,
            'espera_mediana_dias', case when w.waiting < 5 then null else w.median_wait end
          ) order by sp.name)
          from public.service_specialties ss
          join public.specialties sp on sp.id = ss.specialty_id
          left join lateral (
            select count(*) as waiting,
                   round((percentile_cont(0.5) within group (order by extract(epoch from now() - q.entered_at) / 86400))::numeric, 0) as median_wait
            from public.queue_entries q
            where q.service_id = ss.service_id and q.specialty_id = ss.specialty_id and q.status = 'aguardando'
          ) w on true
          where ss.service_id = s.id and ss.active
        ), '[]'::jsonb)
      ) order by s.name)
      from public.services s where s.active
    ), '[]'::jsonb),
    'rede', jsonb_build_object(
      'pessoas_acompanhadas', (select count(distinct patient_id) from public.queue_entries where status = 'em_atendimento'),
      'atendimentos_ultimos_30_dias', (select count(*) from public.appointments where status = 'presente' and scheduled_for >= now() - interval '30 days' and scheduled_for <= now()),
      'taxa_comparecimento_30_dias', (select round(100.0 * count(*) filter (where status = 'presente')
                                        / nullif(count(*) filter (where status in ('presente','falta_justificada','falta_injustificada')), 0), 0)
                                      from public.appointments where scheduled_for >= now() - interval '30 days' and scheduled_for <= now()),
      'encaminhamentos_respondidos_30_dias', (select count(*) from public.referrals where responded_at >= now() - interval '30 days')
    )
  )
$$;
revoke all on function public.public_network_overview() from public, anon, authenticated;
grant execute on function public.public_network_overview() to service_role;

grant execute on function public.search_agent_knowledge(text, integer) to service_role;

notify pgrst, 'reload schema';
